import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./grid.css";
import "./globals.css";
import "@/styles/verticleNavigation.css";
import "@/styles/buyShare.css";
import "@/styles/projectCard.css";
import "@/styles/projectDetail.css";
import "@/styles/authtextslider.css";
import "@/styles/responsive.css";

import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
